### ISSUE TITLE
mods 

### ISSUE THREAD

**Issue by deano0158** [Ryhon0/VostokMods#2]
i don't  know how the mods get installed  i have them in the folder just not working

**Comment by Ryhon0** [comment]
Open the mods folder and move the downloaded zip there. There's a link for instructions when you download a mod

**Comment by deano0158** [comment]
i put it in the folder it does not work but do i have to code anything?

**Comment by Ryhon0** [comment]
No. Follow the instructions again

**Comment by deano0158** [comment]
yeah mb i got it sorry for this
